2024-10-25 13:07:52,668 INFO    StreamThr :50288 [internal.py:wandb_internal():86] W&B internal server running at pid: 50288, started at: 2024-10-25 13:07:52.667569
2024-10-25 13:07:52,671 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status
2024-10-25 13:07:52,736 INFO    WriterThread:50288 [datastore.py:open_for_write():87] open: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\run-av0od26r.wandb
2024-10-25 13:07:52,744 DEBUG   SenderThread:50288 [sender.py:send():378] send: header
2024-10-25 13:07:52,823 DEBUG   SenderThread:50288 [sender.py:send():378] send: run
2024-10-25 13:07:53,791 INFO    SenderThread:50288 [dir_watcher.py:__init__():211] watching files in: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files
2024-10-25 13:07:53,791 INFO    SenderThread:50288 [sender.py:_start_run_threads():1099] run started: av0od26r with start time 1729854472.72057
2024-10-25 13:07:53,813 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: check_version
2024-10-25 13:07:53,813 DEBUG   SenderThread:50288 [sender.py:send_request():405] send_request: check_version
2024-10-25 13:07:54,640 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: run_start
2024-10-25 13:07:55,356 DEBUG   HandlerThread:50288 [system_info.py:__init__():26] System info init
2024-10-25 13:07:55,356 DEBUG   HandlerThread:50288 [system_info.py:__init__():41] System info init done
2024-10-25 13:07:55,356 INFO    HandlerThread:50288 [system_monitor.py:start():194] Starting system monitor
2024-10-25 13:07:55,356 INFO    SystemMonitor:50288 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-25 13:07:55,356 INFO    HandlerThread:50288 [system_monitor.py:probe():214] Collecting system info
2024-10-25 13:07:55,370 INFO    SystemMonitor:50288 [interfaces.py:start():190] Started cpu monitoring
2024-10-25 13:07:55,371 INFO    SystemMonitor:50288 [interfaces.py:start():190] Started disk monitoring
2024-10-25 13:07:55,373 INFO    SystemMonitor:50288 [interfaces.py:start():190] Started gpu monitoring
2024-10-25 13:07:55,375 INFO    SystemMonitor:50288 [interfaces.py:start():190] Started memory monitoring
2024-10-25 13:07:55,407 INFO    SystemMonitor:50288 [interfaces.py:start():190] Started network monitoring
2024-10-25 13:07:55,408 DEBUG   HandlerThread:50288 [system_info.py:probe():150] Probing system
2024-10-25 13:07:55,411 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:07:55,411 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:07:55,412 DEBUG   HandlerThread:50288 [system_info.py:_probe_git():135] Probing git
2024-10-25 13:07:55,566 DEBUG   HandlerThread:50288 [system_info.py:_probe_git():143] Probing git done
2024-10-25 13:07:55,566 DEBUG   HandlerThread:50288 [system_info.py:probe():198] Probing system done
2024-10-25 13:07:55,566 DEBUG   HandlerThread:50288 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.19045-SP0', 'python': '3.11.5', 'heartbeatAt': '2024-10-25T11:07:55.408517', 'startedAt': '2024-10-25T11:07:52.645607', 'docker': None, 'cuda': None, 'args': ('False',), 'state': 'running', 'program': 'C:\\Users\\bais_\\source\\repos\\Progetto\\NLP-customer-classification\\src\\scripts\\train.py', 'codePathLocal': 'src\\scripts\\train.py', 'codePath': 'src\\scripts\\train.py', 'git': {'remote': 'https://github.com/giacomobais/NLP-customer-classification.git', 'commit': '92186a1c3fbd5d4e97b4899777b15350347073c8'}, 'email': '57444236+giacomobais@users.noreply.github.com', 'root': 'C:/Users/bais_/source/repos/Progetto/NLP-customer-classification', 'host': 'DESKTOP-3I1KQF4', 'username': 'bais_', 'executable': 'C:\\Users\\bais_\\anaconda3\\python.exe', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2592.0, 'min': 0.0, 'max': 2592.0}, 'cpu_freq_per_core': [{'current': 2592.0, 'min': 0.0, 'max': 2592.0}], 'disk': {'/': {'total': 464.33886337280273, 'used': 430.6695785522461}}, 'gpu': 'NVIDIA GeForce GTX 950M', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 950M', 'memory_total': 4294967296}], 'memory': {'total': 7.901309967041016}}
2024-10-25 13:07:55,566 INFO    HandlerThread:50288 [system_monitor.py:probe():224] Finished collecting system info
2024-10-25 13:07:55,567 INFO    HandlerThread:50288 [system_monitor.py:probe():227] Publishing system info
2024-10-25 13:07:55,567 DEBUG   HandlerThread:50288 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-10-25 13:07:55,807 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\conda-environment.yaml
2024-10-25 13:07:57,448 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:07:57,448 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:07:57,449 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:07:57,449 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:07:59,491 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:07:59,491 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:07:59,493 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:07:59,493 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:01,544 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:01,545 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:01,545 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:01,545 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:03,581 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:03,582 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:03,582 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:03,582 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:05,634 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:05,635 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:05,635 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:05,635 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:07,671 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:07,672 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:07,672 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:07,672 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:09,715 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:09,715 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:09,715 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:09,716 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:11,766 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:11,766 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:11,766 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:11,766 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:13,819 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:13,820 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:13,820 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:13,820 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:15,854 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:15,854 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:15,854 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:15,854 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:17,907 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:17,908 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:17,909 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:17,909 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:19,917 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:19,917 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:19,918 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:19,918 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:21,919 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:21,919 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:21,919 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:21,919 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:23,933 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:23,933 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Unknown Error
2024-10-25 13:08:23,933 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:23,933 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:26,558 ERROR   gpu       :50288 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-10-25 13:08:26,559 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:26,559 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:28,562 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:28,562 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:29,363 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\conda-environment.yaml
2024-10-25 13:08:29,729 DEBUG   HandlerThread:50288 [system_info.py:_save_conda():219] Saving conda packages done
2024-10-25 13:08:29,731 INFO    HandlerThread:50288 [system_monitor.py:probe():229] Finished publishing system info
2024-10-25 13:08:29,756 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:29,757 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: keepalive
2024-10-25 13:08:29,757 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:29,757 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: keepalive
2024-10-25 13:08:29,757 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:29,758 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: keepalive
2024-10-25 13:08:29,758 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:29,758 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: keepalive
2024-10-25 13:08:29,758 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:29,758 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: keepalive
2024-10-25 13:08:29,758 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:29,759 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: python_packages
2024-10-25 13:08:29,759 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: stop_status
2024-10-25 13:08:29,759 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: internal_messages
2024-10-25 13:08:29,759 DEBUG   SenderThread:50288 [sender.py:send_request():405] send_request: python_packages
2024-10-25 13:08:29,760 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:29,761 DEBUG   SenderThread:50288 [sender.py:send_request():405] send_request: stop_status
2024-10-25 13:08:29,965 DEBUG   SenderThread:50288 [sender.py:send():378] send: telemetry
2024-10-25 13:08:29,966 DEBUG   SenderThread:50288 [sender.py:send():378] send: files
2024-10-25 13:08:29,966 INFO    SenderThread:50288 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-10-25 13:08:30,402 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\wandb-metadata.json
2024-10-25 13:08:30,403 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\requirements.txt
2024-10-25 13:08:30,567 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:30,568 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:31,339 INFO    wandb-upload_0:50288 [upload_job.py:push():131] Uploaded file C:\Users\bais_\AppData\Local\Temp\tmpodn3zprgwandb\nyepcp2o-wandb-metadata.json
2024-10-25 13:08:32,429 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_created():271] file/dir created: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:32,575 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:32,576 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:34,462 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:34,586 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:34,588 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:34,588 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:36,594 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:36,594 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:37,631 DEBUG   SenderThread:50288 [sender.py:send():378] send: telemetry
2024-10-25 13:08:38,537 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:38,604 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:38,605 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:39,643 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:40,609 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:40,610 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:41,521 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: stop_status
2024-10-25 13:08:41,522 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: keepalive
2024-10-25 13:08:41,522 DEBUG   SenderThread:50288 [sender.py:send_request():405] send_request: stop_status
2024-10-25 13:08:42,614 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:42,614 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:43,628 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:44,652 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:44,652 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:45,586 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:45,666 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:46,693 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:46,693 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:47,709 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:48,734 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:48,734 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:49,745 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:50,691 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:50,767 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:50,767 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:51,782 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:52,806 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:52,806 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:53,815 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\output.log
2024-10-25 13:08:54,842 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:54,842 ERROR   gpu       :50288 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-10-25 13:08:55,422 DEBUG   SystemMonitor:50288 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-25 13:08:55,423 DEBUG   SenderThread:50288 [sender.py:send():378] send: stats
2024-10-25 13:08:55,691 INFO    memory    :50288 [interfaces.py:monitor():140] Process proc.memory.rssMB has exited.
2024-10-25 13:08:55,692 DEBUG   SystemMonitor:50288 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-25 13:08:55,692 DEBUG   SystemMonitor:50288 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-25 13:08:55,854 DEBUG   SenderThread:50288 [sender.py:send():378] send: stats
2024-10-25 13:08:55,891 ERROR   gpu       :50288 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-10-25 13:08:55,891 DEBUG   HandlerThread:50288 [handler.py:handle_request():146] handle_request: status_report
2024-10-25 13:08:56,904 INFO    Thread-16 :50288 [dir_watcher.py:_on_file_modified():288] file/dir modified: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\files\config.yaml
2024-10-25 13:08:57,869 WARNING StreamThr :50288 [internal.py:is_dead():414] Internal process exiting, parent pid 41340 disappeared
2024-10-25 13:08:57,869 ERROR   StreamThr :50288 [internal.py:wandb_internal():152] Internal process shutdown.
2024-10-25 13:08:57,904 INFO    HandlerThread:50288 [handler.py:finish():869] shutting down handler
2024-10-25 13:08:57,905 INFO    WriterThread:50288 [datastore.py:close():296] close: C:\Users\bais_\source\repos\Progetto\NLP-customer-classification\wandb\run-20241025_130752-av0od26r\run-av0od26r.wandb
2024-10-25 13:08:57,905 INFO    HandlerThread:50288 [system_monitor.py:finish():203] Stopping system monitor
2024-10-25 13:08:57,906 INFO    HandlerThread:50288 [interfaces.py:finish():202] Joined cpu monitor
2024-10-25 13:08:57,907 INFO    HandlerThread:50288 [interfaces.py:finish():202] Joined disk monitor
2024-10-25 13:08:57,907 INFO    HandlerThread:50288 [interfaces.py:finish():202] Joined gpu monitor
2024-10-25 13:08:57,908 INFO    HandlerThread:50288 [interfaces.py:finish():202] Joined memory monitor
2024-10-25 13:08:57,908 INFO    HandlerThread:50288 [interfaces.py:finish():202] Joined network monitor
2024-10-25 13:08:58,059 INFO    SenderThread:50288 [sender.py:finish():1521] shutting down sender
2024-10-25 13:08:58,414 INFO    MainThread:50288 [internal.py:handle_exit():76] Internal process exited
